services:
  ubuntu:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USER: ${USER}
        USER_PWD: ${USER_PWD}
        GIT_TAG: ${GIT_TAG}
    env_file:
      - .env
    container_name: plutus-course
    ports:
      - 8009:8009
    entrypoint: /entrypoint.sh